books/urls.py
from django.urls import path
from . import views


urlpatterns = [
    path("all_books/", views.all_books, name="all_books"),
    path("teens_books/", views.for_teens_view),
    path("adults_books/", views.for_adults_view),
    path("", views.BooksListView.as_view(), name="books_list"),
    path("books/<int:id>/", views.BooksDetailView.as_view()),
    path("books/<int:id>/delete/", views.BookDeleteView.as_view()),
    path("books/<int:id>/update/", views.EditBookView.as_view()),
    path("create_book/", views.CreateBookView.as_view()),
    path("search/", views.SearchListView.as_view(), name="search"),
    path("bio/", views.bio_view),
    path("hobby/", views.hobby_view),
    path("time/", views.time_view),
    path("random/", views.random_view),
]

main_app/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("books.urls")),
    path("", include("users.urls")),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

users/urls.py
from django.urls import path
from . import views

app_name = "users"
urlpatterns = [
    path("register/", views.RegistrationView.as_view(), name="register"),
    path("login/", views.AuthLoginView.as_view(), name="login"),
    path("logout/", views.AuthLogoutView.as_view(), name="logout"),
    path("user_list/", views.UserListView.as_view(), name="user_list"),
]

templates/footer.html
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
<footer class="bg-body-tertiary text-center text-lg-start" data-bs-theme="dark">
  <div class="text-center p-3" style="background-color: rgba(0, 0, 0, 0.05); color: white">
    © 2024 BOOKS 41-1:
    <a class="text-body" href="https://mdbootstrap.com/">MDBootstrap.com</a>
  </div>
</footer>
</body>
</html>

templates/header.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>BOOKS 41-1</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
</head>
<body>
<nav class="navbar navbar-expand-lg bg-body-tertiary fixed-top" data-bs-theme="dark">
  <div class="container-fluid">
    <a class="navbar-brand" href="#">Navbar</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="{% url 'books_list' %}">Home</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'all_books' %}">Books</a>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Dropdown
          </a>
          <ul class="dropdown-menu">
            <li><a class="dropdown-item" href="{% url 'users:register' %}">Регистрация</a></li>
            <li><a class="dropdown-item" href="#">Another action</a></li>
            <li><hr class="dropdown-divider"></li>
            <li><a class="dropdown-item" href="#">Something else here</a></li>
          </ul>
        </li>
        <li class="nav-item">
          <a class="nav-link disabled" aria-disabled="true">Disabled</a>
        </li>
      </ul>
      <form action="{% url 'search' %}" method="GET"  class="d-flex" role="search">
        <input class="form-control me-2" name="q" type="text" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success" type="submit">Search</button>
      </form>
    </div>
  </div>
</nav>
<br><br><br>